# Generated by Django 3.1.3 on 2020-11-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201104_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippping_address',
            new_name='shipping_address',
        ),
    ]
